//! Widget trait surface — the public API for Framework-tier widgets.
//!
//! See the crate-level documentation for the `flui-framework` Tier B
//! role, the "2 structures + 1 cache" model, and the Tier A / B / C
//! dependency direction. This module publishes the trait surface that
//! SF02–SF08 will extend with reconciliation, `BuildCx`, `setState`,
//! and the rest of the Framework feature set.

use crate::Key;

/// An immutable widget configuration in the flui Framework tier.
///
/// `Widget` is the Tier B (`flui-framework`) public surface for app
/// authors and ecosystem widget crates. Implementations are immutable
/// owned config structs, recreated each rebuild, cheap to clone, with
/// no interior mutability. The runtime tree, layout, painting, and
/// hit-testing are owned by [`flui_core::Element`] — `Widget` only
/// describes the desired tree.
///
/// # Engine vs Framework
///
/// `Widget` is intentionally distinct from engine traits in `flui_core`:
///
/// > This is the mutable, entity-backed engine view trait. Views are
/// > `Entity`s that implement [`Render`](flui_core::Render) and may own
/// > runtime state through `Context<Self>`. This is intentionally
/// > distinct from immutable element recipes such as
/// > [`ElementBuilder`](flui_core::ElementBuilder) and from the future
/// > Framework-tier `Widget` API.
///
/// — verbatim from `flui_core::element` module docs (K03).
///
/// In short:
///
/// | Trait | Tier | When to use |
/// |---|---|---|
/// | [`Widget`] | B | Writing a widget for an app or another widget to compose. |
/// | [`flui_core::Render`] | A | Engine-internal mutable view trait for window roots. |
/// | [`flui_core::RenderOnce`] | A | Engine compatibility path for stateless engine recipes. |
/// | [`flui_core::ElementBuilder`] | A | K03 engine substrate; the eventual lowering target of `Widget::build` (SF07 adapter). |
///
/// # SF01 scope
///
/// SF01 publishes the trait surface only. [`Widget::build`] is a
/// **required** method (Amendment 1, 2026-05-12) — SF01 widgets that
/// need a trivial body return the sealed [`Empty`] null widget, and
/// `#[derive(Widget)]` generates this body automatically. Non-trivial
/// `build` bodies require the SF02 reconciliation engine and the SF03
/// `BuildCx` context. SF03 will widen the `build` signature to accept
/// a `&mut BuildCx<'_>` argument; SF01 widgets ported to SF03 require a
/// one-line edit. SF04 fills the [`WidgetState`] body; SF05 lands
/// `setState`. None of those land in SF01.
///
/// # Lifetime capture (edition 2024)
///
/// Under Rust edition 2024 + RPITIT, `fn build(&self) -> impl IntoWidget`
/// captures `'self` in the returned opaque type. The build return value
/// must be consumed before `&self` is invalidated — typically inside the
/// same reconciliation pass. Storing a `Widget::build` return value
/// across an `await` point or in a `Vec<impl IntoWidget>` is not
/// supported in SF01; erasure for heterogeneous storage will land in
/// SF02 / SF07 via `BoxedWidget`.
pub trait Widget: 'static + Sized {
    /// Returns the user-supplied identity key for this widget, if any.
    ///
    /// The default implementation returns `None`; widgets that carry an
    /// explicit `#[widget(key)]` field get an override generated by
    /// `derive(Widget)`. The trait method name `key` is intentionally
    /// the same as the conventional struct field name — matching
    /// Flutter's `Widget.key` precedent. Rust dispatches method calls
    /// via the trait and field access via `self.<field>`, so the dual
    /// naming is unambiguous to the compiler.
    fn key(&self) -> Option<&Key> {
        None
    }

    /// Builds the child widget tree.
    ///
    /// **Required method** (SF01 Amendment 1, 2026-05-12). The original
    /// frozen contract specified a default `unimplemented!()` body, but
    /// that body does not type-check under Rust 1.95: the `!` returned
    /// by `panic!`/`unimplemented!` does not satisfy `impl IntoWidget`
    /// because the blanket `impl<W: Widget> IntoWidget for W` does not
    /// cover `!`, and `impl IntoWidget for !` would require the still-
    /// unstable `feature(never_type)`. SF01 widgets that need a trivial
    /// body return the sealed [`Empty`] null widget:
    ///
    /// ```ignore
    /// impl Widget for Leaf {
    ///     fn build(&self) -> impl IntoWidget {
    ///         Empty
    ///     }
    /// }
    /// ```
    ///
    /// `derive(Widget)` generates this body automatically when the user
    /// does not provide one.
    ///
    /// SF03 will widen the signature to
    /// `fn build(&self, cx: &mut BuildCx<'_>) -> impl IntoWidget`. That
    /// is a breaking trait method change — every existing impl will
    /// need a one-line edit to add the `cx` parameter.
    fn build(&self) -> impl IntoWidget;
}

/// Sealed null widget — the SF01 trivial `Widget::build` return.
///
/// SF01 widgets that have no children (or that exist only to populate
/// trait-surface tests) return `Empty` from their `Widget::build`
/// implementation. The [`derive(Widget)`](flui_macros::Widget) macro
/// generates this body automatically when the struct does not provide
/// one. `Empty::build` returns `Empty` itself, which type-checks via
/// the [`IntoWidget`] blanket impl.
///
/// **Not intended for general use beyond SF01.** The SF02+ widget
/// catalogue should rely on `Container`, `SizedBox`, `Spacer`, or
/// domain-specific "empty" widgets rather than `Empty`. `Empty` exists
/// in `flui-framework`'s public surface only as a sealed placeholder
/// for the SF01-phase chicken-and-egg problem (the trait needs at
/// least one concrete widget that satisfies `Widget::build` without
/// referencing another widget). See SF01 spec §"Amendment 1".
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Hash)]
pub struct Empty;

impl Widget for Empty {
    fn build(&self) -> impl IntoWidget {
        Empty
    }
}

/// Conversion contract into a [`Widget`].
///
/// Mirrors [`flui_core::IntoElement`] — the engine convention for build
/// / render methods that may produce a value either directly implementing
/// the target trait or wrapped in a small adapter. Every [`Widget`] is
/// also `IntoWidget` via a blanket impl.
///
/// # Object safety
///
/// `IntoWidget` is **not** object-safe and the contract is **sealed
/// against `dyn` use**. The combination of an associated type
/// ([`IntoWidget::Widget`]) and a by-value receiver
/// ([`IntoWidget::into_widget`]) cannot be vtable-dispatched. SF02 /
/// SF07 type-erasure for heterogeneous widget storage uses a separate
/// `BoxedWidget` newtype (to be designed in SF07) — not
/// `dyn IntoWidget`. Implementors that want erasure must go through
/// `BoxedWidget`.
///
/// # Coherence note for SF02+ planners
///
/// The blanket `impl<W: Widget> IntoWidget for W` is the only
/// `IntoWidget` impl SF01 ships. The blanket hardcodes
/// `<W as IntoWidget>::Widget = W` (identity mapping). Any future SF
/// spec that wants to ship a sibling blanket — e.g.,
/// `impl<W: StatefulWidget> IntoWidget for W` — will collide with the
/// existing blanket via coherence, because `StatefulWidget: Widget`.
/// The path forward in that scenario is a non-`Widget` wrapper newtype
/// (e.g., the future `BoxedWidget`, a `WidgetChildren` collection)
/// that implements `IntoWidget` with a non-identity `Widget`
/// associated type. SF01 commits to this pattern as the canonical
/// erasure path.
pub trait IntoWidget {
    /// The concrete [`Widget`] produced by this conversion.
    type Widget: Widget;

    /// Convert `self` into its [`Widget`].
    fn into_widget(self) -> Self::Widget;
}

impl<W: Widget> IntoWidget for W {
    type Widget = W;

    fn into_widget(self) -> W {
        self
    }
}

/// A widget whose mounted element owns mutable state across rebuilds.
///
/// SF01 publishes the trait shape only. The [`WidgetState<Self>`] body
/// arrives in SF04 (`build` / `did_update_widget` / `dispose` methods),
/// and `setState`-driven rebuilds land in SF05. In SF01, implementing
/// `StatefulWidget` lets you publish a `State` factory but no body —
/// the runtime cannot yet mount the widget.
///
/// # Example
///
/// ```
/// use flui_framework::{Key, StatefulWidget, Widget, WidgetState};
///
/// struct Counter {
///     initial: i32,
///     key: Option<Key>,
/// }
///
/// impl Widget for Counter {
///     fn key(&self) -> Option<&Key> {
///         self.key.as_ref()
///     }
///     fn build(&self) -> impl flui_framework::IntoWidget {
///         flui_framework::Empty
///     }
/// }
///
/// impl StatefulWidget for Counter {
///     type State = CounterState;
///     fn create_state(&self) -> CounterState {
///         CounterState { value: self.initial }
///     }
/// }
///
/// struct CounterState {
///     value: i32,
/// }
///
/// // The WidgetState body is empty in SF01; SF04 will add build /
/// // did_update_widget / dispose methods. Implementing the marker is
/// // supported-but-discouraged before SF04.
/// impl WidgetState<Counter> for CounterState {}
///
/// // Surface only: `Counter::create_state()` is callable now, but the
/// // returned state has no behavior yet.
/// let counter = Counter { initial: 0, key: None };
/// let state = counter.create_state();
/// assert_eq!(state.value, 0);
/// ```
pub trait StatefulWidget: Widget {
    /// The state object created at mount time for each instance of
    /// this widget in the element tree. The state survives rebuilds
    /// of its parent and is keyed by the host element's `ElementId`.
    type State: WidgetState<Self>;

    /// Creates the state object. Called once per element, at mount.
    fn create_state(&self) -> Self::State;
}

/// Per-element mutable state companion to a [`Widget`].
///
/// **Stability: UNSTABLE until SF04.** SF01 ships the marker trait only
/// — the body (`build` / `did_update_widget` / `dispose` methods) lands
/// in SF04. Implementing this trait outside of trait-surface tests is
/// supported but actively discouraged before SF04 because SF04 will add
/// required methods, which is a breaking change for any out-of-tree
/// implementor. Treat this trait as a forward-declared identifier
/// whose presence in SF01 only exists so that
/// [`StatefulWidget::State`] has a non-blank bound to point at.
///
/// SF04 will add (signatures subject to that spec's freeze):
///
/// - `fn build(&mut self, cx: &mut BuildCx<'_>) -> impl IntoWidget`
/// - `fn did_update_widget(&mut self, old: &W) {}`
/// - `fn dispose(&mut self) {}`
///
/// Transitively `W: Sized` via the [`Widget`] super-trait bound — so a
/// hypothetical `dyn Widget` is rejected by the type system as a `W`
/// for `WidgetState<W>`.
pub trait WidgetState<W: Widget>: 'static {
    // SF01 ships an empty body; SF04 adds the methods listed above.
}
